# https://fedoramagazine.org/using-ansible-setup-workstation/
# ansible-playbook -K post-install.yml

- hosts: localhost
  vars:
    - fedora_version: 32
  tasks:

# Flatpak And GUI Softwares
# flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
# flatpak update
    - name: Add the flathub flatpak repository remote to the user installation
      flatpak_remote:
        name: flathub
        flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
        state: present
    - name: Install Adwaita-dark Theme
      flatpak:
        name: org.gtk.Gtk3theme.Adwaita-dark
        remote: flathub
        state: present
    - name: Install Tilix Terminal
      flatpak:
        name: com.gexperts.Tilix
        remote: flathub
        state: present
    - name: Install Transmission
      flatpak:
        name: com.transmissionbt.Transmission
        remote: flathub
        state: present
    - name: Install Spotify
      flatpak:
        name: com.spotify.Client
        remote: flathub
        state: present
    - name: Install Blender
      flatpak:
        name: org.blender.Blender
        remote: flathub
        state: present
    - name: Install Slack
      flatpak:
        name: com.slack.Slack
        remote: flathub
        state: present
    - name: Install GIMP
      flatpak:
        name: org.gimp.GIMP
        remote: flathub
        state: present
    - name: Install VLC
      flatpak:
        name: org.videolan.VLC
        remote: flathub
        state: present
    - name: VSCode
      flatpak:
        name: com.visualstudio.code
        remote: flathub
        state: present
    - name: X Mind Zen
      flatpak:
        name: net.xmind.ZEN
        remote: flathub
        state: present