# https://fedoramagazine.org/using-ansible-setup-workstation/
# ansible-playbook -K post-install.yml

- hosts: localhost
  vars:
    - fedora_version: 32
  tasks:

# DConf Settings
# You can use `dconf watch /` to know what key has been changed
# gsettings set org.gnome.desktop.interface gtk-theme 'Adwaita-dark'
# gsettings set org.gnome.desktop.input-sources xkb-options "['ctrl:nocaps']"
# gsettings set org.gnome.desktop.input-sources sources "[('xkb', 'us+alt-intl')]"
    - name: Enable Dark Theme
      dconf:
        key: /org/gnome/desktop/interface/gtk-theme
        value: "'Adwaita-dark'"
    - name: Enable Caps Lock as Ctrl
      dconf:
        key: /org/gnome/desktop/input-sources/xkb-options
        value: "['ctrl:nocaps']"
    - name: Set Keyboard layout to US Alt. Inter
      dconf:
        key: /org/gnome/desktop/input-sources/sources
        value: "[('xkb', 'us+alt-intl')]"
    - name: Set Locale Region
      dconf:
        key: /system/locale/region
        value: "'en_GB.UTF-8'"
    - name: Show Date on Clock
      dconf:
        key: /org/gnome/desktop/interface/clock-show-date
        value: "true"
    - name: Show Battery Percentage
      dconf:
        key: /org/gnome/desktop/interface/show-battery-percentage
        value: "true"
    - name: Show Weekdate
      dconf:
        key: /org/gnome/desktop/calendar/show-weekdate
        value: "true"
    - name: Change WM Button Layout
      dconf:
        key: /org/gnome/desktop/wm/preferences/button-layout
        value: "'appmenu:minimize,maximize,close'"
    - name: Enable Night Light
      dconf:
        key: /org/gnome/settings-daemon/plugins/color/night-light-enabled
        value: "true"
    - name: Set Night Light Temperature
      dconf:
        key: /org/gnome/settings-daemon/plugins/color/night-light-temperature
        value: "uint32 5500"
    # Removable Media Handler - Always ask what to do
    - name: Removable Media Handler - Don't run software
      dconf:
        key: /org/gnome/desktop/media-handling/autorun-x-content-start-app
        value: "['']"
    - name: Removable Media Handler - Don't open folder 
      dconf:
        key: /org/gnome/desktop/media-handling/autorun-x-content-open-folder
        value: "['']"
    - name: Removable Media Handler - Don't ignore
      dconf:
        key: /org/gnome/desktop/media-handling/autorun-x-content-ignore
        value: "['']"
    # Empty trash and temp files periodcally
    - name: Empty trash - On
      dconf:
        key: /org/gnome/desktop/privacy/remove-old-trash-files
        value: "true"
    - name: Clean temp files - On
      dconf:
        key: /org/gnome/desktop/privacy/remove-old-temp-files
        value: "true"
    - name: Set trash and temp files age (days)
      dconf:
        key: /org/gnome/desktop/privacy/old-files-age
        value: "uint32 30"
    # Privacy settings
    - name: Disable location services
      dconf:
        key: /org/gnome/system/location/enabled
        value: "false"
    # Screen Lock
    - name: Enable screen lock
      dconf:
        key: /org/gnome/desktop/screensaver/lock-enabled
        value: "true"
    - name: Screen lock delay after blank screen (seconds)
      dconf:
        key: /org/gnome/desktop/screensaver/lock-delay
        value: "uint32 0"
    - name: Screen blank screen delay (seconds)
      dconf:
        key: /org/gnome/desktop/session/idle-delay
        value: "uint32 120"
    - name: Remove from search
      dconf:
        key: /org/gnome/desktop/search-providers/disabled
        value: "['org.gnome.Contacts.desktop', 'org.gnome.Calendar.desktop', 'org.gnome.Characters.desktop', 'org.gnome.clocks.desktop', 'org.gnome.Terminal.desktop', 'org.gnome.Software.desktop']"
    # Dash to Dock
    - name: Dash to Dock - Shrink dock
      dconf:
        key: /org/gnome/shell/extensions/dash-to-dock/custom-theme-shrink
        value: "true"
    - name: Dash to Dock - Don't show Application button
      dconf:
        key: /org/gnome/shell/extensions/dash-to-dock/show-show-apps-button
        value: "false"
    - name: Dash to Dock - Not fix dock on desktop
      dconf:
        key: /org/gnome/shell/extensions/dash-to-dock/dock-fixed
        value: "false"
    - name: Dash to Dock - Set Panel Mode
      dconf:
        key: /org/gnome/shell/extensions/dash-to-dock/extend-height
        value: "true"
    - name: Dash to Dock - Disable Autohide
      dconf:
        key: /org/gnome/shell/extensions/dash-to-dock/autohide
        value: "false"
    - name: Dash to Dock - Disable Intellihide
      dconf:
        key: /org/gnome/shell/extensions/dash-to-dock/intellihide
        value: "false"
    - name: Dash to Dock - Running Indicator
      dconf:
        key: /org/gnome/shell/extensions/dash-to-dock/running-indicator-style
        value: "'DASHES'"
    - name: Dash to Dock - Set Fixed Opacity
      dconf:
        key: /org/gnome/shell/extensions/dash-to-dock/transparency-mode
        value: "'FIXED'"
    - name: Dash to Dock - Background Opacity
      dconf:
        key: /org/gnome/shell/extensions/dash-to-dock/background-opacity
        value: "1.0"
    - name: Dash to Dock - Use Custom Background Color
      dconf:
        key: /org/gnome/shell/extensions/dash-to-dock/custom-background-color
        value: "true"
    - name: Dash to Dock - Background Color
      dconf:
        key: /org/gnome/shell/extensions/dash-to-dock/background-color
        value: "'#000000'"
    - name: Dash to Dock - Icon Size
      dconf:
        key: /org/gnome/shell/extensions/dash-to-dock/dash-max-icon-size
        value: "32"