# https://fedoramagazine.org/using-ansible-setup-workstation/
# ansible-playbook -K post-install.yml

- hosts: localhost
  vars:
    - fedora_version: 32
  tasks:

# Packages
    - name: Install Ansible DConf Module Dependency
      become: yes
      package:
        name: python3-psutil
        state: present
    - name: Install RPM Fusion Repository
      become: yes
      dnf:
        name: 
          - "http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ fedora_version }}.noarch.rpm"
          - "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ fedora_version }}.noarch.rpm"
        state: present
    - name: Install Media Codecs
      become: yes
      package:
        name: "{{ packages }}"
      vars:
        packages:
        - gstreamer1-libav 
        - gstreamer1-plugins-bad-free-extras 
        - gstreamer1-plugins-bad-freeworld 
        - gstreamer1-plugins-base-tools 
        - gstreamer1-plugins-good-extras 
        - gstreamer1-plugins-ugly 
        - gstreamer1-plugins-bad-free 
        - gstreamer1-plugins-good 
        - gstreamer1-plugins-base 
        - gstreamer1
        - ffmpeg
        - compat-ffmpeg28 
        - ffmpeg-libs
        - libmatroska
        - chromium-libs-media-freeworld
    - name: Install SeaHorse to encrypt and decrypt files easily
      become: yes
      package:
        name: "{{ packages }}"
      vars:
        packages:
        - seahorse
        - seahorse-nautilus
    - name: Install Other Tools
      become: yes
      package:
        name: "{{ packages }}"
      vars:
        packages:
        - vim
        - htop
        - gnome-tweaks
        - gnome-shell-extension-dash-to-dock

# Install ZSH
# dnf install -y zsh
# sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
# sudo usermod -s /usr/bin/zsh yourlogin
# add to path (zshrc)
# $HOME/.local/bin
    - name: Install ZSH
      become: yes
      package:
        name: zsh
        state: present
    - name: Download Oh-My-Zsh
      get_url:
        url: https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh
        dest: ~/
        mode: 0740
    - name: Install Oh-My-Zsh
      command: sh -c "~/install.sh"
      register: omzsh_install
      changed_when: omzsh_install.rc == 0
      failed_when: 
        - omzsh_install.rc != 0
        - omzsh_install.rc != 1
    - name: Change Zsh Theme
      lineinfile: 
        dest: ~/.zshrc 
        regexp: "^ZSH_THEME=(.*)" 
        line: 'ZSH_THEME="gianu"' 
        state: present 
        backup: yes 
        backrefs: yes
    - name: Add Open Alias to Zsh config
      lineinfile: 
        dest: ~/.zshrc 
        line: 'alias open="xdg-open"' 
        state: present 
        backup: yes 
    - name: Add dnf cache Alias to Zsh config
      lineinfile: 
        dest: ~/.zshrc 
        line: 'alias dnf="dnf --cacheonly --color=auto"' 
        state: present 
        backup: yes 
    - name: Set PATH on Zsh config
      lineinfile: 
        dest: ~/.zshrc 
        regexp: "export PATH=(.*)" 
        line: 'export PATH=$HOME/.local/bin:$PATH' 
        state: present 
        backup: yes 
        backrefs: yes
    - name: Change user's shell
      become: yes
      command: usermod --shell /usr/bin/zsh {{ ansible_user_id }}
      register: userm
      changed_when: '"no changes" in userm.stdout'