- hosts: localhost
  tasks:

# Install ZSH
# dnf install -y zsh
# sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
# sudo usermod -s /usr/bin/zsh yourlogin
# add to path (zshrc)
# $HOME/.local/bin
    - name: Install ZSH
      become: yes
      package:
        name: zsh
        state: present
    - name: Download Oh-My-Zsh
      get_url:
        url: https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh
        dest: ~/
        mode: 0740
    - name: Install Oh-My-Zsh
      command: sh -c "ZSH='$HOME/.local/share/oh-my-zsh' ~/install.sh"
      register: omzsh_install
      changed_when: omzsh_install.rc == 0
      failed_when: 
        - omzsh_install.rc != 0
        - omzsh_install.rc != 1
    - name: Change user's shell
      become: yes
      command: usermod --shell /usr/bin/zsh {{ ansible_user_id }}
      register: userm
      changed_when: '"no changes" in userm.stdout'
    - name: Clean install
      file:
        path: ~/install.sh
        state: absent

