- name: Create Projects directory
  file:
    path: ~/Projects
    state: directory

- name: Clone Public Personal Repositories
  git:
    dest: "~/Projects/lucasqlm/{{ item }}"
    repo: "https://github.com/lucasqlm/{{ item }}.git"
  loop:
    - python-webapp
    - linux-post-install